// <auto-generated> This class was generated. Do not modify by hand. </auto-generated>
using System.Globalization;
using System.Resources;

namespace ImeEdgeBar;

/// <summary>
/// Strongly-typed accessors for localised UI strings.
/// Falls back to the neutral (English) resource set when no satellite assembly
/// matches the current UI culture.
/// </summary>
internal static class Strings
{
    private static readonly ResourceManager _rm =
        new("ImeEdgeBar.Strings", typeof(Strings).Assembly);

    private static string Get(string name) =>
        _rm.GetString(name, CultureInfo.CurrentUICulture) ?? name;

    // ── Context menu ────────────────────────────────────────────────────
    public static string Menu_ToggleVisibility          => Get(nameof(Menu_ToggleVisibility));
    public static string Menu_Settings                  => Get(nameof(Menu_Settings));
    public static string Menu_About                     => Get(nameof(Menu_About));
    public static string Menu_Exit                      => Get(nameof(Menu_Exit));

    // ── Tray icon tooltip ────────────────────────────────────────────────
    public static string Tray_ImeOn                     => Get(nameof(Tray_ImeOn));
    public static string Tray_ImeOff                    => Get(nameof(Tray_ImeOff));

    // ── Settings form ────────────────────────────────────────────────────
    public static string Settings_Title                 => Get(nameof(Settings_Title));
    public static string Settings_Position              => Get(nameof(Settings_Position));
    public static string Settings_Top                   => Get(nameof(Settings_Top));
    public static string Settings_Bottom                => Get(nameof(Settings_Bottom));
    public static string Settings_Left                  => Get(nameof(Settings_Left));
    public static string Settings_Right                 => Get(nameof(Settings_Right));
    public static string Settings_BarSize               => Get(nameof(Settings_BarSize));
    public static string Settings_Thickness             => Get(nameof(Settings_Thickness));
    public static string Settings_ThicknessUnit         => Get(nameof(Settings_ThicknessUnit));
    public static string Settings_ImeOn                 => Get(nameof(Settings_ImeOn));
    public static string Settings_Color                 => Get(nameof(Settings_Color));
    public static string Settings_ColorPick             => Get(nameof(Settings_ColorPick));
    public static string Settings_Opacity               => Get(nameof(Settings_Opacity));
    public static string Settings_ImeOff                => Get(nameof(Settings_ImeOff));
    public static string Settings_Cancel                => Get(nameof(Settings_Cancel));
    public static string Settings_ShowMousePointerIndicator => Get(nameof(Settings_ShowMousePointerIndicator));
}
